language: python
python:
  - 2.7
install:
  - pip uninstall -y numpy
  - sudo apt-get install -y python-numpy
script:
  - export PYTHONPATH=/usr/lib/python2.7/dist-packages:$PYTHONPATH
  - python check-numpy.py
  - python speedtest.py
